spring:
  h2:
   console:
     enabled: true
     path: /h2-ui
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

