spring:
  datasource:
    url: jdbc:h2:mem:localdb
    driverClassName: org.h2.Driver
    username: sa
    password:



server:
  port: 9090


person:
  details:
    name: arun
    location: Hyd
    country: india
  data: personData

sample:
  data1: value1
  data2: value2